/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administracion.aeropuertos;

import gui.envios.*;
import beans.Aeropuerto;
import beans.Envio;
import beans.Escala;
import beans.Parametro;
import beans.Vuelo;
import controllers.CAeropuerto;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ronald
 */
public class MonitoreoFrame extends javax.swing.JDialog {

    /**
     * Creates new form MonitoreoFrame
     */
    beans.Aeropuerto objAero = null;
    private List<Aeropuerto> ListaAeropuerto = null;
    public MonitoreoFrame(beans.Aeropuerto ObjAero) {
        initComponents();
         ListaAeropuerto = CAeropuerto.GenerarListaAeropuerto();
        objAero = ObjAero;
    }
     
    public Aeropuerto ShowDialog() {

      setVisible(true);
       
      return objAero;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
               Graphics c = this.getGraphics();
        
        for (int j = 0; j <ListaAeropuerto.size(); j++){
            
                 c.setColor(Color.WHITE);
                 
                 c.drawString(ListaAeropuerto.get(j).getPais().getValor()+'-'+ListaAeropuerto.get(j).getNombre(), ListaAeropuerto.get(j).getCoordX()+15, ListaAeropuerto.get(j).getCoordY());
                 c.setColor(Color.red);
                 c.fillOval(ListaAeropuerto.get(j).getCoordX(), ListaAeropuerto.get(j).getCoordY(), 10,10 );
              
                 c.drawOval(ListaAeropuerto.get(j).getCoordX(), ListaAeropuerto.get(j).getCoordY(), 10,10 );
                // c.draw3DRect(, rootPaneCheckingEnabled);
                         
                // c.drawRect(ListaAeropuerto.get(j).getCoordX(), ListaAeropuerto.get(j).getCoordY(), 10,10 );
                 
           }  
        c.setColor(Color.GREEN);
        c.fillOval(objAero.getCoordX(),objAero.getCoordY(), 10,10 );
              
        c.drawOval(objAero.getCoordX(),objAero.getCoordY(), 10,10 );
        
            
                
        
       /* if (envio == null) {
            return;
        }

        if (envio.getEscalas() == null) {
            return;
        }

        for (Escala e : envio.getEscalas()) {
            Vuelo v = e.getVuelo();

            if (v == null) {
                continue;
            }

            Parametro p = v.getEstado();

            if (p == null) {
                continue;
            }

            if (p.getValorUnico().equals("CAN")) {
                g.setColor(Color.RED);
            }

            if (p.getValorUnico().equals("FIN")) {
                g.setColor(Color.BLUE);
            }

            if (p.getValorUnico().equals("PROG") || p.getValorUnico().equals("RET")) {
                g.setColor(Color.YELLOW);
            }

            if (p.getValorUnico().equals("VUE")) {
                g.setColor(Color.GREEN);
            }

            Aeropuerto o = v.getOrigen();
            Aeropuerto d = v.getDestino();

            if (o != null && d != null) {
                Graphics2D g2 = (Graphics2D) g;
                Stroke stroke = new BasicStroke(2.0f);
                g2.setStroke(stroke);
                g2.drawLine(o.getCoordX(), o.getCoordY(), d.getCoordX(), d.getCoordY());
            }

        }

        g.dispose();
        
        
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Monitoreo Envio");
        setMinimumSize(new java.awt.Dimension(1024, 582));
        setModal(true);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/world-map1024x582.PNG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        int x_posicion;
        int y_posicion;
        x_posicion = evt.getX();
        y_posicion = evt.getY();
        Graphics g = this.getGraphics();
          objAero.setCoordX(x_posicion);
          objAero.setCoordY(y_posicion);
          g.setColor(Color.WHITE);  
          g.fillOval(x_posicion, y_posicion, 10,10 );
              
          g.drawOval(x_posicion, y_posicion, 10,10 );
          g.drawString(objAero.getPais().getValor()+'-'+objAero.getNombre(), x_posicion + 15, y_posicion);
          int result = 0;
   
         
          result =  JOptionPane.showConfirmDialog(null, "Desea asignarle otra ubicacion ?", "Confirmaciòn",JOptionPane.YES_NO_OPTION);
         
          if (result == JOptionPane.NO_OPTION ) {
                 this.dispose();
          }
             
         
        
    }//GEN-LAST:event_jLabel1MousePressed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitoreoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitoreoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitoreoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitoreoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitoreoFrame(new beans.Aeropuerto()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
